language: ruby
rvm: 2.1
env:
  global:
    secure: X7utB2ezc6c/XyKBqbvgaa2Vu7RqcfGbCIxOEbA9wZ7Ke2/0XxpB8EtZ3TmLP/XWpHWTv0e6gHeZ/CPIFi0jg6Z974GVObk3irHyZ76t3aQfcziSznkX6mvfPmQgVEXT7dFwJAKwh40TzSbIZewP+eH8i80c39CfCVtxAUV2KNmhYmzSvSBjvO7HrQNVTz73CaIgqJxuHmNU5UsXfCwVFQl7C4IXqU6ZcI2sh78bGEgKma/Aw2jQmxckhxinx0MmBDmzF+x5Qa5KU7xFvyWHdgl8KRLqkpLnBcDW0fPZvrDnwlx/86vSopVDcxM/Ee8FHkhWaL3WUOBNzjCfsn1E6gS/tieJCSMt3FayevfVj6w41F4VxPc5kPV5ampz8lpRjbth2woUXxE2vApKs1/a7Vjow1Ob+ThUeSLwezyr65KyBPbIeVk7G1offHKA8FUDDee75UakMatmvyVvf8y7IlF3lj3NrgsGHFv2QozANpllA6cb9eCZM/uDWWgpwHLetQukuK/oC8I6jqV8Ur73KCMiUfFRZG10s8wol7JFOK9BbYU2i3dzgzMo8s+OqpITILcwT2lNJ49PfGkAIZ6JwS1q4dGV/Fi+ZWWXDcLx5GOoKaLVhDNUIBDj8Zp/AqHUaxsXrPIGMAxsoeUpZ3qq6lRfQ5gDVsJVg82jurdsRZU=
install: gem install jekyll -v 2.4.0 cf-s3-invalidator
script: jekyll build
deploy:
  provider: s3
  access_key_id: AKIAJ77MISS2AXMDZ65A
  secret_access_key:
    secure: Movjy1aRfy2OJkZuSdV9M5tm4cPW1pYPmCKzFJr6xOQ8LrcfKODwQk/bsz/pyYeTkIiHBlQMPvSE5Mof5TjkEBlYExEBd3KG+o9RxC5q1Z1DOxT2pc5ZKmg0Fo9ji8dHnhmLZDuM8OXOwUkCLKc690B6gdvL8x73WgHgaOI9VHwSn9baxX4LhmU9GbhAMe4N/pcxJOCE4aLAfZ9pd+MvUBmeNCLuPi6raEvWIn7fk0HFYf4+/2xUBg7fcdfXiiWYCx1m8Z6+qIX3OUyIdweZy/b1WJkQxfakPivev4JOezS5YvNxNUeIicV4T6VIqauaL0g3UVvggRlF66cMNUHokBl8OFrKlMnZEum/dB6tPHTJrB+6z0XcYePlLX9VvZXcTLtE63KW/kVqc19fVdA/VF17ealxX/LNPGJ17NIKayevSNuDYFTeVYXCurCQmZl9PuwlqFyQrlD9t70VZNJRga4LvP75MrdUfMK6C/whWyi9+S0XOQKLp46P0JR4TQyxHPgRa3rZUsTaT3wwhG/PLY7OObbpFvxmHs9bHvr9IUoeOsi0rUrsms9MkbJXg2IECzbx0Zn17Yxo7Eyjcsv0fAU5MVZrOHii3DXXXG7TIkG4SIYYp/9J9HfngEj3iiqQroBSgIfM+UZwDMJ2NDeq9aoxKSWxH7333oAPfm8796Y=
  bucket: jameshale.me
  on:
    branch: master
  local_dir: "./_site"
  skip_cleanup: true
after_deploy: cf-s3-inv --key AKIAJ77MISS2AXMDZ65A --secret ${AWS_SECRET_ACCESS_KEY} --distribution EJ67OLBDSYP63
