language: ruby
rvm: 2.4.1
env:
  global:
install: gem install jekyll:3.6.2
script: jekyll build
deploy:
  provider: s3
  access_key_id: AKIAJ4RQKULZGZW6W6ZQ
  bucket: jameshale.net
  on:
    branch: master
  local_dir: "./_site"
  skip_cleanup: true
  after_deploy:
    - _deploy/cf_purge.sh
notifications:
  slack:
    rooms:
