language: ruby
rvm: 2.4.1
env:
  global:
    secure: X7utB2ezc6c/XyKBqbvgaa2Vu7RqcfGbCIxOEbA9wZ7Ke2/0XxpB8EtZ3TmLP/XWpHWTv0e6gHeZ/CPIFi0jg6Z974GVObk3irHyZ76t3aQfcziSznkX6mvfPmQgVEXT7dFwJAKwh40TzSbIZewP+eH8i80c39CfCVtxAUV2KNmhYmzSvSBjvO7HrQNVTz73CaIgqJxuHmNU5UsXfCwVFQl7C4IXqU6ZcI2sh78bGEgKma/Aw2jQmxckhxinx0MmBDmzF+x5Qa5KU7xFvyWHdgl8KRLqkpLnBcDW0fPZvrDnwlx/86vSopVDcxM/Ee8FHkhWaL3WUOBNzjCfsn1E6gS/tieJCSMt3FayevfVj6w41F4VxPc5kPV5ampz8lpRjbth2woUXxE2vApKs1/a7Vjow1Ob+ThUeSLwezyr65KyBPbIeVk7G1offHKA8FUDDee75UakMatmvyVvf8y7IlF3lj3NrgsGHFv2QozANpllA6cb9eCZM/uDWWgpwHLetQukuK/oC8I6jqV8Ur73KCMiUfFRZG10s8wol7JFOK9BbYU2i3dzgzMo8s+OqpITILcwT2lNJ49PfGkAIZ6JwS1q4dGV/Fi+ZWWXDcLx5GOoKaLVhDNUIBDj8Zp/AqHUaxsXrPIGMAxsoeUpZ3qq6lRfQ5gDVsJVg82jurdsRZU=
install: gem install jekyll:3.6.2 cf-s3-invalidator
script: jekyll build
deploy:
  provider: s3
  access_key_id: AKIAJ4RQKULZGZW6W6ZQ
  secret_access_key:
    secure: aFC9JYMj2CPR5CY1SSjR2m6wfXL01Myzz9pfAaagGp2ZNVjd5HMMKnAl9ocujcr8Ho8Vd98UljLFiC+h97yzd674A78FvrW5km4Fl8bTSdUQq+0H6z284YY5ePiC4Bh5YXpchxGVO6EmUTpIfxkVf0DZLwdPabO6+tH0GYo9ihk2r0sWyybuG96imYXh+B64tTJXSqB6a//ImyttQ9bMbUvsZ1GJoHEr7IgP3Yv23noXDiqhP5GmKn75R/Vu5P3gLj5sIf3iYk6RJpTlyBdbaoaRMx4v+juB2qsBujpz6JkS6OTIxWjHuxvSc3j0VoTg8yFwMOp2gnh3MLH2CPDfnaawjhUByzWffkvnGRux/cZRTwxavKkRDG9nFu8GhO9jDAeRbc9eRG1hYOoMdcZQnNEMpOgEdA6ayYJQIwnMPnWiU88fHoCnKyU242XD0NI8zYnCpuTIiEUNL/vKwy214Z2yC8CQ7Fb9iwLSioql97TheaQCveEmpL4tmlkpRWx9Fi+tel4b4iPRKlgr1nYxT85W0Xn1mkLTRAZJiEF1fvuPV2LgUVI5jv0K8NuGIeaHgpBfR44Yx3KNnQqC0JlCDAfwSpQSKwSnm8FRdn4IhantA9ag8FNimnqD8itYi1x+o1OI+J71L90DipeRO8gXKBACavncT7ve+1169yKyJ3o=
  bucket: jameshale.me
  on:
    branch: master
  local_dir: "./_site"
  skip_cleanup: true
after_deploy: cf-s3-inv --key AKIAJ4RQKULZGZW6W6ZQ --secret ${AWS_SECRET_ACCESS_KEY}
  --distribution EJ67OLBDSYP63
notifications:
  slack:
    rooms:
      secure: K93eIEhcJg1Rt5Rr9+wfaxwd7aajfpWNHy+s1FvG5xzsBpABQK0HQ45nu6FyMZlXixzKMIjVYECSJA8IHTuuYkK9Xh9I53dtkrihom2WQKHPP5Ick7r+1MIgFC1KdRLEEoDj5T+rtmk2UQMgQdJGH77GmY7+aKC5wS5oSZ9ukwpr03/6sRehTDRVv4rtz4wgRmgkcIAtfiZTclM4WRS2sDwpFM8NTTJqqWGAvM8sldwXlk20tubbL9aA3DajNiJ+nlD6gMsvljRZGPHFCLFrUAERxntF68HIaJwJbsvQqikKFdci82n8fChaMI3JYxBM6jqlGFsY/nDH7+6esIk/+wkZCSaDQCArpjBW5EpaCUSse8XI7ctNpiWn7zcFnZPTBLiBLY/dqv3HZ/FxMwng8U9tmqJFsKCXsm7pZQ6IO2MjRbl8e0WSS0kUWFPHcqJ3tbZrpOy9okYNZ1yokW3eREuVYVIuvZXb0U3Ohcs5a8r/WhccJkC0ML016R2VR1w6iJx8CtzY7Jrs0VWhZpzqqfff1F9scXXgbTtByXxfFHwBIEIRyRW1PZWVf0rycwkvf8/KrH5sGHabV05v5lotu6eBUYELVUsuNukh2Ur76Gg2vbOE4gaVKTUKirgPFyQ7rIJR6w+YCU1NhWyzflm0NGP9RkQN00jrWPudhmZdDHw=
